-- This migration was originally created to introduce workflow status enums,
-- campaignPageId, and a GenerationJobPage uniqueness invariant.
--
-- The committed Prisma schema never adopted those changes:
-- - workflow status fields remain String columns
-- - WordpressPublishLog does not define campaignPageId
-- - GenerationJobPage does not define a unique [jobId, pageId] constraint
--
-- The schema changes actually used by the application were already captured by:
-- - 20260302000100_add_publishlog_job_correlation
-- - 20260302002000_reconcile_manual_schema_drift
--
-- Leaving the original SQL here causes deploys to fail on databases that
-- correctly match the checked-in schema, so this migration is intentionally a
-- no-op.
